package com.maxcogito.auth.domain;

public enum RoleName {
    ROLE_USER, ROLE_ADMIN, ROLE_SECURITY_SERVICE, ROLE_DATA_SERVICE,ROLE_DATA_ANALYTIC_SERVICE,ROLE_IDENTITY_SERVICE,ROLE_COMMODITY_ANALYTIC_SERVICE
}
